### ISSUE TITLE
NameError: name 'process_prompt_for_tulu' is not defined

### ISSUE THREAD

**Issue by JamesJang26** [yale-nlp/LLM-T2T#1]
Hello for interesting and great research! 

I've got an error while running Table-to-Text Generation by Open-Source Models, with no other changes. The detailed error message is as below.

"""
Traceback (most recent call last):
  File "/home/james/LLM-T2T/scripts/../src/open_src_model_T2T_generation.py", line 17, in <module>
    "tulu": process_prompt_for_tulu,
NameError: name 'process_prompt_for_tulu' is not defined
Traceback (most recent call last):
  File "/home/james/LLM-T2T/scripts/../src/open_src_model_T2T_generation.py", line 17, in <module>
    "tulu": process_prompt_for_tulu,
NameError: name 'process_prompt_for_tulu' is not defined
"""

It would be greatful if you let me know how to deal with the problem I've faced.

**Comment by yilunzhao** [comment]
Hi @JamesJang26, thanks for your interests in our work!

The `process_prompt_for_tulu` function, which is used for preprocessing input prompts for tulu-* models, can be found at https://github.com/yale-nlp/LLM-T2T/blob/2822c05fb69ac38f86ee7325040c9aa93fc19d8f/utils/open_src_model_prompt_utils.py#L26-L27 

We've updated our README files. Please make sure to add the line `export PYTHONPATH=$(pwd);` before running the Python files.

If you encounter any further issues or have questions, feel free to re-open the issue. Thanks!
