### ISSUE TITLE
Request for requirements.txt to Simplify Environment Setup for llm-t2t Repository

### ISSUE THREAD

**Issue by hongzzi-zzi** [yale-nlp/LLM-T2T#2]
Hello `llm-t2t` team,

I am currently working with the `llm-t2t` repository and finding it challenging to set up the correct environment due to the absence of a `requirements.txt` file. This file is crucial for ensuring consistent environment configuration, especially when dealing with complex dependencies.

It would be immensely helpful for users like myself if you could provide a `requirements.txt` file. This file would list all the necessary Python packages and their respective versions to run the project successfully.

I believe this addition will greatly enhance the usability of the `llm-t2t` repository and aid others who may face similar challenges.

Thank you for considering this request.

**Comment by yilunzhao** [comment]
Hi @hongzzi-zzi, thank you for your suggestions for the codebase improvment! We have added the `requirements.txt` file and updated the [README](https://github.com/yale-nlp/LLM-T2T?tab=readme-ov-file#environment-setup).  

If you encounter any further issues or have questions, feel free to re-open the issue. Thanks!
